### PR TITLE
feat: fix reactivity problem between withdrawal form and amount range component

### LINKED ISSUE #42: [Task]: Fix reactivity problem between withdrawal form and amount range component
There seems to be a reactivity issue with the withdrawal form and the amount range component. The withdrawal feature should always contain at least the min storage deposit in it for the transaction to be succesful, and this leads to the users having to enter manually the base token amount. We should fix it so the minimum is really the minimum storage deposit. 

Additionally, there seems to be an issue with the min of the input range and the storage deposit, it should be 287500 micro/glow which is 0.287500 base tokens, but the value taken is much smaller

### PR DESCRIPTION
**Pull request by evavirseda**
# Description of change

## Links to any relevant issues

fixes #42 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes
- [ ] I have updated the CHANGELOG.md, if my changes are significant enough

### CODE REVIEW

File: src/components/inputs/amount-range.svelte [hunk 1]
```diff
@@ -15,6 +17,17 @@
   $: maxValueFormatted = max / 10 ** decimals;
   $: valid = value >= min && value <= max;
 
+  onMount(() => {
+    value = Math.max(min, Math.min(max, value));
+    valueFormatted = value / 10 ** decimals;
+  });
+
+  // Make sure the component updates the internal state when value prop changes
+  afterUpdate(() => {
```
Comment (begonaalvarezd) [inline src/components/inputs/amount-range.svelte:26]: im not sure about this, you are blocking the possibility of editing the input manually without using the range

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — APPROVED** [review]
